### ISSUE TITLE
This object will not be created in future versions. Please report this to the developer - Details L1 false Details L2 false Details L3 false

### ISSUE THREAD

**Issue by papadebaer** [iobroker-community-adapters/ioBroker.sma-em#105]
Hi there,
I get the following error message. Is the adapter still up-to-date and functional?

`
`

host.pi | 2021-01-03 17:29:56.211 | info | Update repository "Stable (default)" under "http://download.iobroker.net/sources-dist.json"
-- | -- | -- | --
sma-em.0 | 2021-01-03 17:28:01.488 | warn | (5740) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2021-01-03 17:28:01.487 | warn | (5740) Object sma-em.0.1900204704.psurpluscounter is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
sma-em.0 | 2021-01-03 17:28:01.477 | warn | (5740) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2021-01-03 17:28:01.477 | warn | (5740) Object sma-em.0.1900204704.psurplus is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
sma-em.0 | 2021-01-03 17:28:01.475 | warn | (5740) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2021-01-03 17:28:01.474 | warn | (5740) Object sma-em.0.1900204704.pregardcounter is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
sma-em.0 | 2021-01-03 17:28:01.473 | warn | (5740) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2021-01-03 17:28:01.472 | warn | (5740) Object sma-em.0.1900204704.pregard is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
sma-em.0 | 2021-01-03 17:28:01.470 | warn | (5740) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2021-01-03 17:28:01.469 | warn | (5740) Object sma-em.0.1900204704.SMASerial is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
sma-em.0 | 2021-01-03 17:28:01.463 | warn | (5740) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2021-01-03 17:28:01.462 | warn | (5740) Object sma-em.0.1900204704 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
sma-em.0 | 2021-01-03 17:28:00.689 | info | (5740) Details L1 false Details L2 false Details L3 false
sma-em.0 | 2021-01-03 17:28:00.688 | info | (5740) Listen via UDP on Port 9522 for Multicast IP 239.12.255.254
sma-em.0 | 2021-01-03 17:28:00.634 | info | (5740) starting. Version 0.5.7 in /opt/iobroker/node_modules/iobroker.sma-em, node: v10.23.0, js-controller: 3.1.6
host.pi | 2021-01-03 17:27:59.008 | info | instance system.adapter.sma-em.0 started with pid 5740
host.pi | 2021-01-03 17:27:56.998 | info | iobroker exit 0
host.pi | 2021-01-03 17:27:55.981 | info | iobroker host.pi object system.adapter.sma-em.0 created

`
Pi 4 (4.1.11)

**Comment by DutchmanNL** [comment]
please retest with new version
