### ISSUE TITLE
no configuration possible, File index.html not found

### ISSUE THREAD

**Issue by Sniplow** [iobroker-community-adapters/ioBroker.sma-em#127]
**Describe the bug**  
"Adapterkonfiguration: sma-em.0"
File index.html not found

i have installed the Adapter, but i can't reach the configuration.

**Versions:**  
 - Adapter version: 0.6.1-beta.0
 - JS-Controller version: 3.1.6
 - Node version:  v12.20.1
 - Operating system: ioBroker in Docker Synology DSM

**Comment by pdbjjens** [comment]
@Sniplow 
Did you install 0.6.1-beta.0 over an existing previous version? If so, you could try uninstalling the adapter completely and reinstall 0.6.1-beta.0. It would be helpful if you would provide a screenshot  of the installation and of the iobroker log.

**Comment by Sniplow** [comment]
i had no installed previous version, but i tried one in the past.
i have already tried to reinstall the Adapter last time, but nothing has changed.

i have just reinstalled the adapter for the log, and now it works.
Thank You!
