### ISSUE TITLE
Incompatible with JS controller 3.2.16?

### ISSUE THREAD

**Issue by Percy2Live** [iobroker-community-adapters/ioBroker.sma-em#133]
Adapter doesn't start (independent of adapter version) after update to js controller 3.2.16

![log](https://user-images.githubusercontent.com/63621052/108891753-5fdf7880-760f-11eb-9e16-0f3c6a062498.png)

**Comment by TGuybrush** [comment]
The adapter needs at least the Node.js 12. The latest version is v12.20.2 which provides the readBigUInt64BE. Please check your Node.js version.

**Comment by Percy2Live** [comment]
After updating node.js to the latest version the adapter runs fine. Maybe it should be added to the changenotes that a certain node.js version is required for any newer version than 0.5.6

Thanks for your advice!
