### ISSUE TITLE
warn: sma-em.0 (9509) State "sma-em.0.3009872298.pregard" has no existing object

### ISSUE THREAD

**Issue by pdbjjens** [iobroker-community-adapters/ioBroker.sma-em#152]
**Describe the bug**  
When the adapter is started, numerous warnings like: 
"warn: sma-em.0 (9509) State "sma-em.0.3009872298.pregard" has no existing object, this might lead to an error in future versions" 
appear in the iobroker log (see attached logfile).

**To Reproduce**  
The warnings appear at each startup of the adapter. The js-controller version needs to be 3.2.x; the warnings do not appear with js-controller 3.1.x

**Expected behavior**  
No warnings should appear, regardless of js-controller version.
It seems that a setState is done for non-existant states. A create state or extendObjectNotExists seems to be missing.

**Screenshots & Logfiles**  
[sma-em-063-errlog.txt](https://github.com/iobroker-community-adapters/ioBroker.sma-em/files/6210434/sma-em-063-errlog.txt)

**Versions:**  
Adapter version: <0.6.3>
JS-Controller version: <3.2.16>
Node version: <v12.21.0>
Operating system: <linux arm>

**Additional context**  
None

**Comment by TGuybrush** [comment]
I've pushed a new version for testing in my repository.

**Comment by pdbjjens** [comment]
@TGuybrush 
I have reinstalled your new version in my environment and it starts just fine. The warnings are gone.
![Startup-warnings-Screenshot 2021-04-11 163101](https://user-images.githubusercontent.com/60287544/114308427-3e195280-9ae4-11eb-8aac-aa4a06c85e2f.jpg)


Thank you for fixing this. I think it is not necessary to have others test it before the next official release. So please include your fixes in your next PR for version 0.6.4 
Will you be able to implement #142 soon so that we can include it in 0.6.4? Or should we better release 0.6.4 with the fixes you implemented up to now and make a new release for #142 ? What do you think?

**Comment by TGuybrush** [comment]
I'm working on #142 but it will take same time. I propose to release the new version now since it's better to do incremental  improvements to detect potential problems.

**Comment by pdbjjens** [comment]
@TGuybrush 
I agree. I think your proposal makes much sense. Will you then provide a PR for a version 0.6.4 with your latest fixes, please. I will take care that it will be released and communicate it on the beta test thread in the forum so that we hopefully get some additional test feedback.

**Comment by pdbjjens** [comment]
v0.6.4 has been released to stable. The problem is fixed with this version.
