### ISSUE TITLE
Warnings observed like "State value to set for "sma-em.0.1901713852.cosphi" has to be type "state" but received type "number""

### ISSUE THREAD

**Issue by Markus7501** [iobroker-community-adapters/ioBroker.sma-em#191]
I observ for all objects warnings like:
State value to set for "sma-em.0.1901713852.cosphi" has to be type "state" but received type "number"

IOB version: v 5.1.9
Node version: v12.22.1
NPM version: 6.14.12
JS Version:3.x
Adapter version: 0.6.3

**Comment by pdbjjens** [comment]
@Markus7501 
Will be fixed with Adapter v0.6.4 (the current version on github). It would be great if you would test v0.6.4 by installing it from github and report any remaining issues here.

**Comment by peoples0815** [comment]
Habe den gleichen Fehler, wenn ich aber den Adapter über Git installiere, bleibt die Version auf 0.6.3

Auf NPM ist auch nur die 0.6.3 verfügbar

**Comment by pdbjjens** [comment]
Ja, ist so. Wir werden sobald wie möglich die Github Version als v0.6.4 auf npm freigeben. Bitte noch etwas Geduld.

09.08.2021 10:57:09 Steffen ***@***.***>:

**Comment by peoples0815** [comment]
Ahso ok, ich dachte nur weil oben geschrieben steht bitte die 0.6.4 testen, nur konnte ich die nicht installieren zum testen.

**Comment by pdbjjens** [comment]
@peoples0815 @Markus7501 
v0.6.4 has been released to stable. The problem should be fixed at least since this version. 
If you still encounter this issue, please try one of the following procedures:

1. Stop the adapter, delete all objects which are mentioned in the warnings 
(e.g. using the trash bin icon in the Adapter tab or `iobroker del sma-em`)
Restart the adapter. If this does not help:
2. Completly uninstall the adapter and reinstall it.

**Comment by ghoethe** [comment]
i have a fresh installation, but I get the same message:

State value to set for "sma-em.0.3006137891.L3.p3surpluscounter" has to be type "state" but received type "number"

and other ....

**Comment by pdbjjens** [comment]
@ghoethe 
Did you follow the procedure  mentioned above (Aug. 20)?
If you did, please let us know  the version of the sma-em adapter which you are using (should be 0.6.4). Also please specify the iobroker host and nodejs versions. A log file of a restart of the sma-em adapter including the warnings would be helpful.

**Comment by ghoethe** [comment]
Jetzt geht es, er hatte sich nicht die aktuelle v0.6.4 per update gezogen, sorry
