### ISSUE TITLE
Problems with the serial Number in Datapoints in iobroker

### ISSUE THREAD

**Issue by HansPeterMeier** [iobroker-community-adapters/ioBroker.sma-em#20]
Hello,
it is possible to change ne channel name for the SMA Meter?
I have a Problem with iobroker, i think, the problem is the serial number as a channel.
https://forum.iobroker.net/viewtopic.php?f=22&t=19789

It is also possible to set a timeout before the new States? Every second is a little bit to much.

thanks.

**Comment by peoples0815** [comment]
Ich hänge mich hier mal ran, da ich das gleiche Problem habe

**Comment by HansPeterMeier** [comment]
ich habe meine getauscht gegen einen PAC 2200 von Siemens, der über Modbus ausgelesen wird. Die Teile kosten nicht gerade viel und das Thema mit dem SMA hat sich erledigt.
Bezüglich dein Problem mit dem Admin und dem Filtern, du kannst in der JS Main den Code abändern mit einen S davor, dann gehts.

**Comment by peoples0815** [comment]
Ja das mit dem Ändern hatte ich auch gemacht seit dem gehts.

**Comment by peoples0815** [comment]
Habe heute den Adapter neu installiert und wollte nur berichten, dass der Fehler nach wie vor noch vorhanden ist.

Sobald ich den Datenpunkt (Serial) in Anführungszeichen setze ist der Fehler auch weg.

Liegt vermutlich am erstellen:
...
this.setObjectNotExists(ser.toString(), {
					type: 'channel',
				  common: {
				  name: ser,
				 type: 'channel'
					},
...

Die Seriennummer als Zahl für "name" bereitet hier offensichtlich Probleme

**Comment by DutchmanNL** [comment]
please retest with new version
