### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.sma-em#23]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.sma-em

- [ ] [E140] width and height of logo are not equal
- [ ] [E405] Icon must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.sma-em/master/
- [ ] [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.sma-em/master/io-package.json
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/iobroker-community-adapters/ioBroker.sma-em" and press "Manage topics"
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2020 Marcolotti <info@ct-j.de>" at the end of README.md
- [ ] [E816] file tsconfig.json found in repository, but not found in .npmignore

Thanks,
your automatic adapter checker.

**Comment by DutchmanNL** [comment]
fixed

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
