### ISSUE TITLE
Calculation of Total Power Consumption

### ISSUE THREAD

**Issue by stevoboy** [iobroker-community-adapters/ioBroker.sma-em#331]
Dear all

I would like to calculate the total power consumption of the house with Node Red it is displayed in the SMA App on the lower right side. 
Has anybody an idea what objects I need to consider in the calculation. I started a trial but it is quite try and error because the values in the app change as well as in the adapter.

Thanks!

**Comment by pdbjjens** [comment]
@stevoboy 
There has already been a discussion about this topic ongoing in the iobroker forum. [https://forum.iobroker.net/post/740948](https://forum.iobroker.net/post/740948), which offered several possible solutions. Please have a look there and if the answers of the forum  members do not satisfy your needs then I suggest that you ask your question in the forum.
To summarize the solutions of the forum: use the consumption counters either of the SHM (sma-em adapter: pregardcounter) or the inverter (modbus-adapter: register 30581). Compute the daily consumption either via a script or using the statistics-adapter or the sourceanalytix-adapter (at 23:59: daily consumption = countervalue now - countervalue yesterday; countervalue yesterday = contervalue now;)
