### ISSUE TITLE
Latest SMA Update - Extended Data incorrect

### ISSUE THREAD

**Issue by TGuybrush** [iobroker-community-adapters/ioBroker.sma-em#34]
Since the latest update dated 9.12 of the SMA energy meter, the extended or detailed data values become incorrect. It seems that they changed the interface specification.

**Comment by ricott** [comment]
I have observed the same. I have also asked SMA support if they changed the format. The emeter spec on their site was not updated when I checked in the past week. No reply from their support yet.

**Comment by ricott** [comment]
SMA support replied this is not their area to cover, you should be able to email infa@sma they state. I managed to verify that positions have been pushed by 8 though, so adding +8 from L1 info an onwards solves the problem.
I also did a new implementation in my code which doesn't use fixed positions but instead uses their obis identifiers. It is not released in the wild yet, so still waiting on final confirmation that the obis code works on all firmware versions. Anyhow, if interested the code is here, https://github.com/ricott/sma.modbus/blob/master/lib/sma_em.js.

**Comment by Elektronikwelt** [comment]
Hi
I have the same problem with Homemanager 2.0.
It is enough if I only exchange the SMA-EM.js file.
Something has to be configured so that Homemanager 2.0 also works. I still use an SMA energy meter. I have blocked this from the Internet. Will this continue to work with the old software?

**Comment by TGuybrush** [comment]
I've made a pull request with a revised version which solves this problem. 
What's the procedure for a pull request?

**Comment by rolsch** [comment]
- works fine

**Comment by DutchmanNL** [comment]
please retest with new version
