### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.sma-em#341]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.sma-em

- [ ] [E154] common.dependencies must contain{"js-controller": ">=2.0.0"} or {"js-controller": ">=3.0.0"}
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Marcolotti <info@ct-j.de>" at the end of README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Marcolotti <info@ct-j.de>" at the start of LICENSE

Thanks,
your automatic adapter checker.

**Comment by pdbjjens** [comment]
All fixed with Release v0.6.5 Latest

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
