### ISSUE TITLE
Explain the output values

### ISSUE THREAD

**Issue by marvincaspar** [iobroker-community-adapters/ioBroker.sma-em#37]
Can you please explain each output value (auch gerne auf deutsch) and what is the different between L1, L2 and L3.

Are there values for generated electricity, purchased electricity, consumed electricity and electricity which is feed in?
And can I get these values on a weekly base?

**Comment by Elektronikwelt** [comment]
Es sind Momentanwerte die übertragen werden. Diese können über iobroker/history mitgeloggt werden die Beschreibung gibt es hier http://www.eb-systeme.de/?page_id=3005

**Comment by Elektronikwelt** [comment]
L1 L2 L3 sind die einzelnen Phasen der Zuleitungen

**Comment by DutchmanNL** [comment]
nach einem Jahr gehe ich mal davon aus das die frage gekehrt ist ? :)
