### ISSUE TITLE
SMA-EM findet Multicast nicht: UDP Socket error: Error: bind EADDRINUSE 0.0.0.0:9522

### ISSUE THREAD

**Issue by MiRi1975** [iobroker-community-adapters/ioBroker.sma-em#371]
**Describe the bug**  
Adapter ist installiert, Multicast des Sunny Home Managers 2 wurde nicht gefunden, da bei 0.0.0.0:9522 gesucht wird. Die Original Adresse 239.12.255.254 wurde nicht verändert

**To Reproduce**  
Einfach den Adapter starten, er wird dann automatisch mit dem Fehler UDP Socket error: Error: bind EADDRINUSE 0.0.0.0:9522 beendet. Ein iOS App auf meinem Display zeigt mir die Daten einwandfrei und ohne Verzögerung an. 

**Expected behavior**  
Gerät verbindet sich nicht mit dem Dienst

**Screenshots & Logfiles**  
Wie oben geschrieben UDP Socket error: Error: bind EADDRINUSE 0.0.0.0:9
**Versions:**  
 - Adapter version: <0.6.5>
 - JS-Controller version: 4.0.21
 - Node version: 14.19.1
 - Operating system: <Bullseye>

**Comment by pdbjjens** [comment]
@MiRi1975 
Typischerweise kommt so eine Meldung, wenn man versucht eine zweite Instanz zu kreieren. Beim SMA-EM Adapter kann/darf nur eine Instanz (sma-em.0) auf einem System laufen. Schau doch mal, ob noch irgend ein anderer Prozess (möglicherweise auch außerhalb von iobroker) läuft, der auf 239.12.255.254:9522 gebunden ist. Frage: OS-Version? Virtual Machine(Docker)?

**Comment by MiRi1975** [comment]
Genau das ist ja mein Problem. Ich habe keine „1“ Instanz installiert. 
Ich hatte unter Node-Red testweise einen Flow der das konnte. Diesen Flow habe ich aber gelöscht. 
Ebenso bekomme ich ja eben diese gewünschten Infos aus einer iOS app, direkt vom WR, ich denke auch über Multicast, da genau die SMA-EM Multicast Adresse dort auch verwendet wird, wenn ich die App aufrufe. 

Wie kann ich herausfinden, ob mein Raspi (Bullseye) hier irgendwas blockiert? Bin in Sachen Linux und Raspi noch ziemlicher Anfänger. 

Für weitere Hilfe wäre ich dankbar

Michael.

**Comment by pdbjjens** [comment]
@MiRi1975 
Ohne jetzt genau zu verstehen, wie Deine Systemumgebung aussieht - ich würde es mal mit einem Reboot des RasPi versuchen. Kann sein, dass Node-Red noch das Multicast Port belegt. 
Welche iOS App hast Du denn? Da die App nicht auf dem RasPi läuft, kann sie (im Gegensatz zum Node-Red) auch nicht dessen Multicast Port belegen. Daher denke ich dass eher der Node-Red Flow hier die Ursache ist.

**Comment by MiRi1975** [comment]
Hallo nochmal,
die Ursache meines Problems in iOBroker und dem SMA-EM Adapter liegt anscheinend in dem installierten EVCC. Wenn ich den mit sudo systemctl stop evcc anhalte, dann funktioniert unter iOBroker auch der SMA-EM Adapter. Nun habe ich versucht auf einer Synology iObroker im Docker zu installieren, aber dort brachte der Adapter ebenfalls bei aktiviertem EVCC keine Werte. Gibt es eine andere Möglichkeit EVCC und iObroker mit SMA-EM Adapter im gleichen Netz zu betreiben? Oder habe ich bei der Synology irgendwelche Portfreigaben übersehen?

**Comment by MiRi1975** [comment]
Es scheint zu klappen, wenn man im Docker die Funktion bei Netzwerk: im selben Host (oder so ähnlich) anhakt. Dann braucht man keine Portweiterleitungen
