### ISSUE TITLE
Logfile Info to developer of JS-Controller 3.0.17

### ISSUE THREAD

**Issue by svenp** [iobroker-community-adapters/ioBroker.sma-em#40]
After upgrade of JS-Controller to version 3.0.17 and nodejs v12.16.2 i found this entry in the info Logfile.
Can you correct this please. 
Thank you

--
sma-em.0 | 2020-04-23 08:53:34.302 | warn | (25365) This will be refused in future versions. Please report this to the developer.
sma-em.0 | 2020-04-23 08:53:34.302 | warn | (25365) The id 1900014133 has an invalid type!: Expected "string" or "object", received "number".
sma-em.0 | 2020-04-23 08:53:33.804 | warn | (25365) This will be refused in future versions. Please report this to the developer.
sma-em.0 | 2020-04-23 08:53:33.804 | warn | (25365) The id 1900014133 has an invalid type!: Expected "string" or "object", received "number".
sma-em.0 | 2020-04-23 08:53:33.300 | warn | (25365) This will be refused in future versions. Please report this to the developer.

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.sma-em/commit/d3a9b3e7622d2d4cd534d25e44c9f3fd1a6ed910
