### ISSUE TITLE
Two Interfaces attached to iobroker/Raspi: SMA-EM listen on wrong Interface

### ISSUE THREAD

**Issue by Flippo710** [iobroker-community-adapters/ioBroker.sma-em#403]
**Describe the bug**  
I have to networks attached to Raspi and iobroker. My Solar SHM is attached to wlan0 instead of eth0. The adapter listens to eth0 instead of wlan0. So i can't reach my SHM.

**To Reproduce**  
1. Install adapter
2. Go to Logs
3. `Listen via UDP on Device eth0 with IP XXX.XXX.XXX.XXX on Port 9522 for Multicast IP 239.12.255.254`

**Versions:**  
 - Adapter version: 0.6.5
 - Operating system: Raspi

**Additional context**

**Comment by TGuybrush** [comment]
The adapter binds to all interfaces which have a valid IPv4 address when the adapter is started. Can you confirm that the wlan0 device has a valid IPv4 address?

**Comment by pdbjjens** [comment]
@Flippo710 
Could you please check your network configuration (e.g. using ifconfig -a ) to see if anything is wrong with your wlan0 interface as @TGuybrush suggested? Are there any other relevant messages in the iobroker log?

**Comment by Flippo710** [comment]
Sorry Guys, I was in vacation :)

I tried to reinstall the adapter again, now, it listens to both interfaces:

![grafik](https://user-images.githubusercontent.com/89018334/174253310-f74d78e7-467c-49cd-823b-ea71ce342bb5.png)

But still no connection. So I turned up Wireshark on the PI and found the following packets:

![grafik](https://user-images.githubusercontent.com/89018334/174255171-00795d84-af66-466d-86af-72c98859b65a.png)

So there is definitly traffic arriving at the PI from the SHM (its the 192.168.0.5!)

Any idea?

**Comment by pdbjjens** [comment]
@Flippo710 
What do you mean by "no connection"? Does the Instance connection indicator in the instance Tab turn green? Is the Object tree in the Objects Tab (sma-em.0) generated? I suggest that we continue the discussion in the iobroker forum where you already posted your problem. Maybe some other users have also ideas.

**Comment by Flippo710** [comment]
Hey,

yep, I have a tree, which is empty.

And I have no conection to a device or service...:

![grafik](https://user-images.githubusercontent.com/89018334/174303307-0f9e214b-0576-4c41-a275-4cfac59c29e8.png)

**Comment by pdbjjens** [comment]
@Flippo710 
Did you configure direct meter communication in Sunny Portal?
Regarding the wireshark recording: Can you filter on the multicast destination ip 239.12.255.254? SMA-EM does not listen on dest ip 192.168.0.255

**Comment by Flippo710** [comment]
No, I didnt configure direct meter communication...(well, I didn't read anything about it, or that I have to configure it...)


And I get no packages from this MC :(

**Comment by pdbjjens** [comment]
You should not configure direct meter communication unless you absolutely need it because of network issues. So we can rule out this as a problem. If you do not get udp packages from 239.12.255.254 the most likely reason is that your network infrastructure (routers, switches) does not properly forward IGMP packages from the SHM to your RPI. In which network are the inverters? I assume in the same network as the SHM? do the inverters receive the SHM multicasts?

**Comment by pdbjjens** [comment]
@Flippo710 
Has this issue been resolved meanwhile so that I can close it?

**Comment by krafel** [comment]
I have actually the same problem when I assign multiple IPs to one NIC. The last version working for me is 0.6.1-beta.0. I still have this version in production. It would be helpful to be able to choose which IP to use.

**Comment by pdbjjens** [comment]
@krafel 
As mentioned by @TGuybrush above, the adapter binds to all interfaces which have a valid IPv4 address when the adapter is started. Thus if your network is configured correctly and the SHM multicasts arrive on any of the bound interfaces, the sma-em adapter should start. Would you please provide an iobroker log of the startup of the sma-em and other relevant information on your system like sw-versions and network configuration  (e.g. using ifconfig -a ) so that we can figure out what goes wrong.

**Comment by Rennsemme5** [comment]
@pdbjjens here I have teh same Issue.

![image](https://user-images.githubusercontent.com/122732602/221570911-aff09492-504f-4e74-be1d-a25e33acf1b8.png)
![image](https://user-images.githubusercontent.com/122732602/221570953-98483982-e646-4e93-8529-b517bb32c387.png)

The log of the start of sma-em is like the following
![image](https://user-images.githubusercontent.com/122732602/221572273-151f82ce-4fc4-4f51-8786-faf2b3905675.png)


Hope you could help me out and get the sma-em adapter running.

Many thanks and kindest regards
Rainer

**Comment by Rennsemme5** [comment]
Sorry, included one picture twice. The correct log of the startup of the sma-em should be this one:
![image](https://user-images.githubusercontent.com/122732602/221601808-bb75780c-e661-4d5b-89a3-6834b317b939.png)

SW-Versions:
ioBroker 6.3.5 on a raspberry pi
SMA-EM-Adapter 0.6.5
SMA devices are STP7000TL-20 and ev charger and sunnyhomemanager 2.0 connected over a switch with a fritz box cable 6591.

For the network configuration I don't know exactly, which information you need. There is no special configuration used.

**Comment by pdbjjens** [comment]
@Rennsemme5 
in which network are the SMA components? The same as the RasPi  i.e. 192.168.178.xxx ? Is the STP connected via WLAN?
SHM and EVC are probably connected via eth?
What type of switch is it?

**Comment by Rennsemme5** [comment]
Yes, the SMA components are within the same network as the RasPi. all components are connected with LAN. The switch is the one which is proposed from SMA. It is the [TP-Link TL-SF1005D](https://www.amazon.de/gp/product/B000FNFSPY/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1).
On the RaspPi is only the ioBroker with less adapters running. It is my first ioBroker and I'm still at the beginning.

**Comment by Rennsemme5** [comment]
The other adapters are
![image](https://user-images.githubusercontent.com/122732602/221630905-878081c6-9e84-4671-90b0-dc9ed5800b11.png)

I don't need WLAN on RasPi. You think I should turn it off directly at the raspi

direct metering is configurated.
"Bezug und Einspeisung" = Internes Energy Meter
"PV-Erzeugung" = kein Zähler
"Messintervall internes Energy Meter:" 200 ms
Direkte Zähler Kommunikation: Gerät 1 = IP of Discovergy energy meter; Gerät 2 = IP of Sunny Tripower inverter; Gerät 3 = IP of EV Charger.

Hope that helps a little bit

**Comment by Rennsemme5** [comment]
yes, direct meter communication was the reason. I deaktivated it and now it looks great. So I have to follow up, if there are problems on the SMA products without direct comunication. Hopefully not. Many thanks for your help.
