### ISSUE TITLE
Invalid value (state) is still ongoing :-(

### ISSUE THREAD

**Issue by EberAr** [iobroker-community-adapters/ioBroker.sma-em#41]
Hi Guy's,
this is my first message in GitHub and also in thisn area :-). 
I have installed the iobroker-adapter and it seems still an invalid state in the interface
Bye Arwed

**To Reproduce**  
I have deleted all adapter and new installed. It seems to be reproduceable.

**Expected behavior**  
Hopefully: a bugfixed release... :-)

**Screenshots & Logfiles**  

sma-em.0 | 2020-05-27 11:43:27.873 | warn | (1886) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
sma-em.0 | 2020-05-27 11:43:27.872 | warn | (1886) Object sma-em.0.3004911124.psurpluscounter is invalid:  obj.common.type has an invalid value (state) but has to be one of  number, string, boolean, array, object, mixed, file, json
sma-em.0 | 2020-05-27 11:43:27.862 | warn | (1886) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2020-05-27 11:43:27.861 | warn | (1886) Object sma-em.0.3004911124.psurplus is invalid: obj.common.type  has an invalid value (state) but has to be one of number, string,  boolean, array, object, mixed, file, json
sma-em.0 | 2020-05-27 11:43:27.859 | warn | (1886) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2020-05-27 11:43:27.858 | warn | (1886) Object sma-em.0.3004911124.pregardcounter is invalid:  obj.common.type has an invalid value (state) but has to be one of  number, string, boolean, array, object, mixed, file, json
sma-em.0 | 2020-05-27 11:43:27.857 | warn | (1886) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2020-05-27 11:43:27.856 | warn | (1886) Object sma-em.0.3004911124.pregard is invalid: obj.common.type  has an invalid value (state) but has to be one of number, string,  boolean, array, object, mixed, file, json
sma-em.0 | 2020-05-27 11:43:27.854 | warn | (1886) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2020-05-27 11:43:27.853 | warn | (1886) Object sma-em.0.3004911124.SMASerial is invalid: obj.common.type  has an invalid value (state) but has to be one of number, string,  boolean, array, object, mixed, file, json
sma-em.0 | 2020-05-27 11:43:27.849 | warn | (1886) This object will not be created in future versions. Please report this to the developer.
sma-em.0 | 2020-05-27 11:43:27.848 | warn | (1886) Object sma-em.0.3004911124 is invalid: obj.common.name has an  invalid type! Expected "string" or "object", received  "number"
sma-em.0 | 2020-05-27 11:43:27.471 | info | (1886) Details L1 false Details L2 false Details L3 false
sma-em.0 | 2020-05-27 11:43:27.470 | info | (1886) Listen via UDP on Port 9522 for Multicast IP 239.12.255.254
sma-em.0 | 2020-05-27 11:43:27.409 | info | (1886) starting. Version 0.5.7 in /opt/iobroker/node_modules/iobroker.sma-em, node: v10.20.1, js-controller: 3.1.4

**Versions:**  
 /node_modules/iobroker.sma-em, node: v10.20.1, js-controller: 3.1.4
 - Operating system: Raspberry Pi

**Comment by EberAr** [comment]
It seems, that the issue is solved with  js-controller: 3.1.6!!!
Thanks for the changes and the system in gerneral!

**Comment by robertfraefel** [comment]
Just updated to 3.1.6 but still the same issue.

**Comment by peoples0815** [comment]
> 
> 
> Just updated to 3.1.6 but still the same issue.

same at my system

**Comment by DutchmanNL** [comment]
please retest with new version
