### ISSUE TITLE
Bedeutung der States

### ISSUE THREAD

**Issue by Tagiwara** [iobroker-community-adapters/ioBroker.sma-em#42]
Kein wirkliches Issue, eher eine Frage: Wo kann man denn herausfinden, was die States bedeuten? Was bedeutet denn "pregard", "psurplus" usw.?

**Comment by Tagiwara** [comment]
Danke schön für die zahlreichen Antworten

**Comment by CTJaeger** [comment]
Steht doch hier in der readme.md
https://github.com/iobroker-community-adapters/ioBroker.sma-em
