### ISSUE TITLE
Incorrect values on L1,L2,L3 for Sunny Home Manager 2.0

### ISSUE THREAD

**Issue by p3pp0** [iobroker-community-adapters/ioBroker.sma-em#43]
**Describe the bug**  
L1: always show 5000 Watts
Regardcounters show silly values, sum values are correct

**To Reproduce**  
use Adapter with Sunny Home Manager 2

**Expected behavior**  
correct values also in single phases

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/9203649/90965835-10878680-e4cc-11ea-90b1-b62283e1e8ba.png)

**Versions:**  
 - Adapter version: 0.5.7

**Comment by andiling** [comment]
Adapter is NOT compatible to Home Manager 2.0

**Comment by p3pp0** [comment]
@andiling Thank you very much for your fast response

Adapter is working perfectly fine with Sunny Home Manager 2.0 - i know lots of people using it..
The only thing are the single Phase values that are wrong...

What would be neccessary to add support for it? Is there anything i can contribute?
