### ISSUE TITLE
No reading of Pregard with HM 2

### ISSUE THREAD

**Issue by electric-m** [iobroker-community-adapters/ioBroker.sma-em#448]
Hey y'all,

I do get 0 W for pregard in iobroker while every other object is giving the correct readings.
Any chance to solve this?

**Comment by pdbjjens** [comment]
@electric-m 
It is quite normal that pregard is zero while psurplus has some positive value. This happens, when your PV system feeds power into the grid. When you receive power from the grid, then pregard has a positive value and psurplus is zero.

**Comment by electric-m** [comment]
Correct, understand it now.
