### ISSUE TITLE
How can I see the current performance

### ISSUE THREAD

**Issue by philg1234** [iobroker-community-adapters/ioBroker.sma-em#514]
Hey,

how can i see the current performance or how can i calculate this with the values?

Thanks.

Regards,
Phil

**Comment by pdbjjens** [comment]
@philg1234 
I am not sure what you mean by current performance, but I suggest that you read the SMA-EM test thread starting at: 
[https://forum.iobroker.net/topic/43011/test-adapter-sma-em-v0-6-x-latest/101](https://forum.iobroker.net/topic/43011/test-adapter-sma-em-v0-6-x-latest/101)
You may find an answer to your question there.
