### ISSUE TITLE
Communication fault

### ISSUE THREAD

**Issue by HJGratz** [iobroker-community-adapters/ioBroker.sma-em#532]
After the adapter has been started, communication between the SMA Tripower and Homemanager breaks off after a few minutes.
Communication works again as soon as the adapter is stopped.

Versions:  
 - Adapter version: 0.7.0
 - SUNNY TRIPOWER 10.0 SE, software 1.21.2.R, firmware 3.1.9.R
 - Sunny Home Manager 2.0
 - SL-Bridge 0.20.0 with 32,5 kWh battery

All software was updated to latest versions, bus is undependend SL-Bridge.

Without communication, the display of the inverter is faulty/incorrect and no control can take place because there are no reference values ​​from the Home Manager
![bug](https://user-images.githubusercontent.com/128484943/226617082-ff9e671c-c721-4cfd-8202-e8314299961a.JPG)
![ok](https://user-images.githubusercontent.com/128484943/226617086-fb30b131-121d-4f90-b72f-287c36bdbfb4.JPG)

**Comment by pdbjjens** [comment]
@HJGratz 
This looks much like a network problem. Please check if your network fulfills the SMA requirements regarding multicast capabilities of the network:

`All network components used must support at least version 3 (IGMPv3) of the IGMP protocol. If Ethernet switches are used in the system, it must be ensured that they do not carry out "IGMP snooping". This is the case with most simple switches, with higher-quality "managed" switches this function must be disabled.`

I suggest that you post your question also in the ioBroker Forum, maybe there are users who have experience with configuring your kind of network for SMA multicast.

[https://forum.iobroker.net/topic/43011/test-adapter-sma-em-v0-7-x-latest/242](https://forum.iobroker.net/topic/43011/test-adapter-sma-em-v0-7-x-latest/242)

[https://forum.iobroker.net/topic/1100/sma-wechselrichter/575](https://forum.iobroker.net/topic/1100/sma-wechselrichter/575)

**Comment by HJGratz** [comment]
@pdbjjens 
Thanks for the hint! After replacing a switch with IGMPv3 (~30€) the problem was solved. The system has now been running for more than 8 hours without this failure (before it was only a few minutes). It looks solved :-)

**Comment by HJGratz** [comment]
# #
