### ISSUE TITLE
Verbindung zu Home Manager 2 nicht möglich

### ISSUE THREAD

**Issue by AxelMeineke** [iobroker-community-adapters/ioBroker.sma-em#541]
Zunächst einmal vielen Dank für die Erstellung des Adapters.
Leider bekomme ich keine Verbindung zum Home Manager 2. Muss ich Multicast separat aktivieren?
IP und Port habe ich unverändert gelassen.
<img width="769" alt="image" src="https://user-images.githubusercontent.com/13676883/233129225-b0bd247c-cdf0-4f73-b284-0bca41ca3147.png">
Verbindung zum Host ist OK
Lebenszeichen ist OK
Verbunden mit Gerät oder Dienst ist nicht ok
<img width="773" alt="image" src="https://user-images.githubusercontent.com/13676883/233129556-462fdda4-aa34-406b-819e-76d77d9fc079.png">

Ich würde mich über Ideen zur Fehlersuche freuen. ich habe keinerlei Einstellungen beim Home Manager angepasst.

**Comment by pdbjjens** [comment]
@AxelMeineke 
Danke fürs Ausprobieren des Adapters. 
Meist liegt so ein Problem im Netzwerk. SMA hat da ganz besondere Anforderungen bzgl. der Multicast-Eigenschaften des Netzwerks.
`Alle verwendeten Netzwerkkomponenten müssen das IGMP-Protokoll mindestens in der Version 3 (IGMPv3) unterstützen. Wenn im System Ethernet Switches verwendet werden, ist sicherzustellen, dass diese kein "IGMP-Snooping" vornehmen. Bei den meisten einfachen Switches ist dies gegeben, bei höherwertigen "gemanagten" Switches ist diese Funktion auszustellen. Bei der Verwendung von Medienkopplern wie z. B. Powerline Adaptern kann es zu Übertragungsproblemen kommen. Meist sind diese Geräte durch einen Firmware-Update des Herstellers für den Multicast-Betrieb zu ertüchtigen.`

Weitere Ursachen können sein: SHM in anderem Subnetz oder VLAN als iobroker, Router, die kein Multicast weiterleiten, Docker Installationen, die Multicast nicht durchschleifen etc. 
Wenn Du diese möglichen Ursachen erfolglos überprüft hast, bräuchte ich etwas mehr Informationen zu Deiner Systemumgebung, um hier weiter helfen zu können . Also:
Adapter version: <0.7.0>
JS-Controller version: 4.?
Node version: 16.??.??
Operating system: RaspiOS?? native oder in Docker?
Verwendete SMA-Komponenten
Netzwerkstruktur (LAN,WLAN,DLAN,VLAN?)
Dann ein iobroker Logfile vom Start des Adapters (wenn möglich vor dem Start des Adapters den Loglevel der Instanz auf "Debug" stellen.
Ansonsten kann ich auch empfehlen, im iobroker Forum [nachzufragen:](https://forum.iobroker.net/topic/43011/test-adapter-sma-em-v0-7-x-latest)

**Comment by AxelMeineke** [comment]
Vielen Dank für die schnelle und kompetente Antwort. Ich befürchte, ich habe das Problem, dass meine Docker-Installation nicht auf Broadcast zugreifen kann. Meine ersten Google-Ergebnisse lassen nicht erahnen, dass ich das navhträglich

**Comment by pdbjjens** [comment]
@AxelMeineke 
Ja, das Problem mit Docker ist schon öfter aufgetaucht. Es wird auch im iobroker/docker [https://hub.docker.com/r/buanet/iobroker](https://hub.docker.com/r/buanet/iobroker) erwähnt. 
Dort wird Umstellung auf MACVLAN  empfohlen.
Ein user hat offenbar durch Umstellung auf "Host" networking das Problem in den Griff bekommen. 
[https://github.com/iobroker-community-adapters/ioBroker.sma-em/issues/371#issuecomment-1100135257](https://github.com/iobroker-community-adapters/ioBroker.sma-em/issues/371#issuecomment-1100135257)
