### ISSUE TITLE
Instance sma-em.0 in Multihost Modus is not starting on Master

### ISSUE THREAD

**Issue by matriedel** [iobroker-community-adapters/ioBroker.sma-em#576]
**Describe the bug**  
Run IoBroker in Multihost Modus

**To Reproduce**  
sma-em.0 is running on Slave without an issue
1. Edit host for sma-em.0 ==> Master
2. Restart 

Connected to host ==> O.K.

Heartbeat ==> O.K.

Connected to device or service ==> Fail

sma-em.0 | 2023-06-22 06:45:03.023 | info | Listen via UDP on Device enp2s0 with IP 192.168.158.37 on Port 9522 for Multicast IP 239.12.255.254
-- | -- | -- | --
sma-em.0 | 2023-06-22 06:45:03.021 | info | Details L1 false Details L2 false Details L3 false Extended info false
sma-em.0 | 2023-06-22 06:45:02.989 | info | starting. Version 0.6.6 in /opt/iobroker/node_modules/iobroker.sma-em, node: v18.16.0, js-controller: 4.0.24

**Versions:**  
sma-em.0.   v0.6.6

Master
Platform: linux
operating system: linux
Architecture: x64
CPUs: 4
Speed: 796 MHz
Model: Intel(R) Celeron(R) N5100 @ 1.10GHz
RAM: 3.6 GB
System uptime: 7 d. 16:26:28
Node.js: v18.16.0
time: 1687409559303
timeOffset: -120
adapters count: 474
NPM: 9.5.1
Disk size: 52.9 GB
Disk free: 28.7 GB
Uptime: 7 d. 16:26:12
Active instances: 18
Path: /opt/iobroker/
alive:

Slave
Platform: docker
operating system: linux
Architecture: x64
CPUs: 4
Speed: 2100 MHz
Model: Intel(R) Atom(TM) CPU C3538 @ 2.10GHz
RAM: 11.6 GB
System uptime: 00:48:35
Node.js: v16.19.1
time: 1687409339448
timeOffset: -120
adapters count: 474
NPM: 9.6.1
Disk size: 16083.2 GB
Disk free: 8104.3 GB
Uptime: 00:46:03
Active instances: 3
Path: /opt/iobroker/
alive:

**Comment by pdbjjens** [comment]
@matriedel 
I suspect some network problems here. Therefore please answer the following questions:
I suppose that Device enp2s0 with IP 192.168.158.37 is the ethernet interface on the master? 
Is the SMA-Energy Meter/Sunny Home Manger in the same network (e.g. 192.168.158.xxx)? 
Is the network in which the master is located forwarding the multicasts of the SMA-EM or SHM to the master?
To which network  did the slave connect to? A log of the startup on the slave would be helpful.

**Comment by pdbjjens** [comment]
@matriedel 
I would really like to help you fix this problem, but to do so, I need the information above from you.

**Comment by pdbjjens** [comment]
@matriedel 
Since I did not receive any response from you up to now, I assume that you solved the problem meanwhile.
Therefore I will close this issue now. If my assumption is wrong, please feel free to reopen  this issue.
