### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.7.0

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.sma-em#577]
# Think about adding version 0.7.0 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.7.0** (104 days old)
**Installs**: stable=**0** (0%), latest=**412** (32.65%), total=**1262**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Comment by mcm1957** [comment]
@pdbjjens 
Any reason to NOT publish this adapter at stable repo?

**Comment by pdbjjens** [comment]
@mcm1957 
There are still two issues open, which I would like to fix and close, This would also involve an new version with some testing period before being published to stable.

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.7.0 but the current stable version is already 0.7.0.

So this issue should be closed.
