### ISSUE TITLE
Voltage is displayed wrong after update 0.7.0

### ISSUE THREAD

**Issue by PilotOffTheWall** [iobroker-community-adapters/ioBroker.sma-em#592]
After updating the adapter to 0.7.0, voltage on an elgris three phase device reads only half the values.

f. ex.: Voltage is 230V as commonly used in germany, but reads 114 Volts.

I couldn't find any switch for fixing this behaviour, so i installed 0.6.6 and everything works just fine again.

**Comment by pdbjjens** [comment]
@PilotOffTheWall 
Since I can not reproduce this behaviour with SMA energy meters, I need you to answer some questions to find out what causes this strange behaviour:
 I assume that the elgris meter behaves differently than the SMA devices, especially regarding the multiast message repetition rate.  The transmission interval of the SMA devices can be set to 200ms, 600ms or 1000ms, At which repetition rate does your Elgris meter send the multicasts? Is the transmission interval stable? What Is your setting for the Real-time update interval? Do other realtime values like power or grid frequency also show differences? An iobroker log including the start-up of the adapter with debug enabled would also be helpful.

**Comment by pdbjjens** [comment]
@PilotOffTheWall 
I need your cooperation to analyse this issue. Without your feedback I will close this issue within the next two weeks. Of course you are free to reopen it then.

**Comment by pdbjjens** [comment]
@PilotOffTheWall 
I am closing this issue due to lack of response. Maybe you could try the latest version 1.0.0 of sma-em and report whether the problem is still present. If so, an iobroker log including the start-up of the adapter with debug enabled would be helpful.

**Comment by PilotOffTheWall** [comment]
Hi,

bitte entschuldige die sehr verspätete Antwort. Leider war ich arbeitstechnisch sehr eingebunden und habe das Problem daher temporär mit revert auf 0.6.6 gelöst. Auch bei Version 1.0.0 bleibt das Verhalten gleich.

Nun zu deinen Fragen:

Ausgehend von meinen Beobachtungen unter 0.6.6 denke ich, es werden alle 1000ms neue Werte geliefert. (Abgeleitet aus last_message Werten)
Der Werte weicht hier ca. +1 - +5 ms ab, das sollte stabil genug sein?
Das Smart-Meter kann ich hier derzeit noch nicht konfigurieren, ich hoffe, da wird ein Firmwareupdate helfen können. Dieses habe ich angefragt, aber noch nicht erhalten

Updateintervall steht auf 1. 

Bisher sind in den für mich relevanten Werten keine weiteren Abweichungen aufgefallen:
![image](https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/27994963/1e314422-1cfc-489a-a9c0-8b11a86d1baf)

Zum Schluss noch ein Screenshot vom Start des Adapters im Debug-Modus:
![image](https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/27994963/76bbc3b8-b9d8-4e79-b0ba-79fca69007b3)


Ich hoffe es hilft dir weiter, bei weiteren Fragen bitte gerne.

Schöne Grüße,
Florian

**Comment by PilotOffTheWall** [comment]
So, das Update der Firmware hat leider keinen Effekt auf das Problem gehabt.
Vielleicht kann dieses Issue wieder geöffnet werden?

Vielen Dank!

**Comment by pdbjjens** [comment]
Danke für die Rückmeldung. Leider kann ich mich wegen anderer Prioritäten zur Zeit nicht mit dem Thema befassen. Ich werde ab Mitte November das Issue wieder aufmachen und mit Deiner Unterstützung schauen, was da los ist.

24.10.2023 16:27:08 PilotOffTheWall ***@***.***>:

**Comment by pdbjjens** [comment]
@PilotOffTheWall
Aus dem obigen Diagramm/Spannungsverlauf entnehme ich, dass in der überwiegenden Zeit die Spannungswerte korrekt  bei 230 V liegen und nur nach 22:00 mehrfach für ein paar Minuten eingebrochen sind auf 115V. Der Spannungsverlauf wurde mit der v1.0.0 und den im Log angegebenen Parametern des Adapters aufgezeichnet. 
Auf dem ioBroker ist kein wlan0 oder eine andere Netzwerkschnittstelle konfiguriert/aktiviert sondern nur eth0. 
Sind meine Annahmen richtig? 

Um das Problem zu analysieren, bitte ich Dich um folgendes: 
Bitte die v1.0.0 über ioBroker Tab "Adapter" installieren (nicht direkt aus GitHub).  In den Multicast-Einstellungen "Verfügbare eigene Netzwerkschnittstellen-IPs" eth0 auswählen (nicht 0.0.0.0) und die Energiezähler-IP 192.168.178.239 eingeben. Unter "Optionen" Echtzeit-Aktualisierungsintervall auf 1. Mehrfach den Adapter starten und stoppen. Ist dann die "message rate" immer = 2/sec ? Wird immer nur auf eth0 auf Multicasts von 192.168.178.239 gelauscht ("Listen via UDP on...") und nicht auf eine weitere  Netzwerkschnittstelle?
Dann bitte die **Zeitstempel** der Realzeitwerte im Tab "Objects" beobachten/loggen, Wie groß ist der Abstand der Zeitstempel der Realzeitwerte genau und wie groß ist deren Varianz? Tritt die Halbierung der Realzeitwerte weiterhin nur sporadisch auf wie im obigen Diagramm? Falls ja, dann bitte die Zeitstempel genau ansehen und wie sie sich von denen im Normalbetrieb unterscheiden. Sind zum Zeitpunkt der Halbierungen Netzwerkstörungen oder andere Veränderungen im  System zu beobachten?
Bitte beachten: Die Objekte TimeTick und last_message können gelöscht werden, da sie seit v1.0.0 obsolet sind und nicht mehr upgedatet werden.

**Comment by PilotOffTheWall** [comment]
Leider sind die Annahmen nicht ganz korrekt. Das obige Diagramm zeigt einen Tagesverlauf mit Version 0.6.0, bei dem am Abend auf Version 1.0.0 geupdatet wurde. Hier treten dann die Werteabweichungen auf. Ich habe den Adapter mehrfach installiert und getestet, daher das auf und ab. ich habe auch getestet, ob eine Neuinstallation des Adapters Abhilfe schafft, dem war leider nicht so. Es gibt nur die eth0 Schnittstelle.

Aktualisiert wird immer über iobroker Adapter.
Die Einstellungen wurden wie angegeben gemacht, Der Adapter startet stets auf eth0 auch die Messagerate variiiert zwischen  2/sec und selten auch 1/sec 
Laut Timestamps variiert die Updaterate um bis zu 75 ms +- um eine Sekunde. 
Bei Messagerate 1/sec traten wurde die Spannung dann im Bereich 450V angezeigt.

ich hoffe, das hilft erst mal weiter. Ich werden demnächst eine zweite Instanz für die Tests aufsetzen, wo der Adapter installiert bleiben kann.

Scgöne Grüße,

**Comment by pdbjjens** [comment]
@PilotOffTheWall 
Danke für die Mühe und die schnelle Aufklärung des Sachverhalts.
Bitte mal das Echtzeit-Aktualisierungsintervall auf 0 setzen. Das schaltet die Mittelwertbildung aus. Danach sollte keine Halbierung der Realzeit-Werte mehr erfolgen. Dann bitte wie vorher den Abstand der Timestamps und deren Varianz beobachten.

**Comment by PilotOffTheWall** [comment]
Danke auch für die Hilfe, jetzt wird alles ordentlich angezeigt. Tatsächlich ist die Varianz des Updateintervalls jetzt deutlich erhöht, zwischen 800 und 1200 ms, wobei er aber meistens innerhalb von +-50ms liegt.

**Comment by pdbjjens** [comment]
@PilotOffTheWall 
Schön, dass es jetzt funktioniert. Ich sehe zur Zeit keine Möglichkeit um das merkwürdige Verhalten des Elgris EM aus der Ferne ohne entsprechende Hardware weiter zu analysieren und ggf. im sma-em anzupassen. 
Daher schlage ich vor, dass Du diese Einstellung (Echtzeit-Aktualisierungsintervall auf 0) beibehältst. Leider musst Du damit auf die Möglichkeit verzichten, die Realzeit-Last zu reduzieren. Aber bei einem Message-Intervall von 1s und nur einem EM lässt sich das wohl verantworten. Außerdem werden wenigstens die Nicht-Realzeitwerte gedrosselt was schon mal eine wesentliche Verbesserung gegenüber v0.6.6 bringt.
Wenn Du damit einverstanden bist, kannst Du dies issue bitte wieder schließen.

**Comment by pdbjjens** [comment]
@PilotOffTheWall 
Hallo, heute bräuchte _ich_ mal Deine Unterstützung. 
Ein anderer User mit Elgris EM hat ein issue  gemeldet #709. Mich würde interessieren, ob Du schon mal ein ähnliches Phänomen beobachtest hast. Das Problem tritt nur bei einem einzigen Datenpunkt (psurplus) auf und kann offenbar auch nicht durch Ausschalten der Mittelwertbildung behoben werden. Könnte das mit einer nicht aktuellen Firmware des Elgris EM oder der Konfigurierung des EM zusammenhängen?
