### ISSUE TITLE
Stromwerte nur Positiv

### ISSUE THREAD

**Issue by Elektrofix-OL** [iobroker-community-adapters/ioBroker.sma-em#595]
Ich brauche die Daten aus dem SMA HM2 um diese per API auf einen SmartEVSE zu bringen.
Dabei stelle ich fest, das der SMA EM Adapter nur positive Stromwert übergibt, obwohl ich ins Netz einspeise und damit der Wert negativ ist.
Meine Frage: Liefert SMA EM die Daten nur positiv, oder wurde das bei dem IoBroker-Adapter extra so gemacht?

**Comment by pdbjjens** [comment]
@Elektrofix-OL 
Die Messwerte vom SHM werden immer als positive Ganzzahlen übermittelt. Der sma-em Adapter multipliziert die Werte nur mit dem jeweiligen Skalenfaktor.
Als Antwort auf die Frage: die Stromwerte sind immer positiv. Die Richtung (Einspeisung oder Bezug) kann man aus den Messpunkten für die Leistung ablesen (z.B. Wirkleistung+ = pregard > 0 bedeutet Bezug, Wirkleistung- = psurplus > 0 bedeutet Einspeisung.
