### ISSUE TITLE
Falsche Werte aus SHM 2.0 (psurplus)

### ISSUE THREAD

**Issue by plustig73** [iobroker-community-adapters/ioBroker.sma-em#627]
Hallo,

Es werden bei mir unstimmige/falsche Werte in den Objekten des sma-em-Adapters angezeigt, aufgefallen beim wert für psurplus.

SHM 2.0 (vor ein paar Wochen wurde eine neue Firmware-Version installiert (2.13.6.R)
sma-em-Apapter Version 1.0

![image](https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/97883553/94b488a7-1a74-42a3-b115-18dff66eb9b6)

Habe ich etwas falsch konfiguriert?

Grüße und vielen Dank

**Comment by pdbjjens** [comment]
@plustig73 
Welchen Wert hat 1... genau? Ist der Wert stabil auf 1... oder ändert er sich? Unter welchen Umständen ist er 1... ?
Ein Protokoll vom Adapter Start wäre hilfreich.
Die Objekte TimeTick und last_message können gelöscht werden, da sie seit v1.0.0 obsolet sind und nicht mehr upgedatet werden.

**Comment by plustig73** [comment]
Hallo, Danke für deine Antwort,

im Screenshot ist es wohl nicht so richtig ersichtlich, habe nochmal einen (zusätzlich noch eine Visualisierung aus dem Victron Portal). Der Wert von psurplus ist nich konstant, sondern schwankt konstant, hat keinen festen Wert.
![image](https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/97883553/d964627a-e34a-4585-bf66-ae9d03deeb56)
Habe den adapter auch mal gelöscht und neu installiert, selbes Verhalten.
Kommt mir fast so vor als wäre es immer ~die Hälfte des korrekten Wertes.

```
sma-em.0 | 2023-09-17 12:08:06.678 | info | New device discovered: Sunny Home Manager 2.0 S/N: 3011838115 with IP/port: 192.168.178.220/46929 message rate: 2/sec
-- | -- | -- | --
sma-em.0 | 2023-09-17 12:08:05.068 | info | Listen via UDP on Network Interface wlan0 with IP 192.168.178.52 on Port 9522 for Multicast IP 239.12.255.254
sma-em.0 | 2023-09-17 12:08:05.067 | info | Listen via UDP on Network Interface eth0 with IP 192.168.178.51 on Port 9522 for Multicast IP 239.12.255.254
sma-em.0 | 2023-09-17 12:08:05.066 | info | Options selected: Details L1 false Details L2 false Details L3 false Extended Mode false RealTime Interval 1 non-Realtime Interval 30 Language: de
sma-em.0 | 2023-09-17 12:08:04.837 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.sma-em, node: v18.17.1, js-controller: 5.0.12
```

Grüße

**Comment by pdbjjens** [comment]
@plustig73 
 wlan0 mit IP 192.168.178.52 und eth0 mit IP 192.168.178.51 sind im selben Netzwerk. Damit empfangen beide dieselben Messages vom SHM mit IP 192.168.178.220. Das führt dazu, dass die Messages zweimal innerhalb des Empfangsintervalls empfangen werden und damit die Messwerte  durch die Mittelwertbildung halbiert dargestellt werden. 
 Um das zu vermeiden bitte in den Multicast-Einstellungen bei "Verfügbare eigene Netzwerkschnittstellen-IPs" eine auswählen (eth0 **ODER** wlan0, nicht 0.0.0.0). Damit sollte das Problem behoben sein.

**Comment by plustig73** [comment]
Hallo @pdbjjens, Vielen Dank, das wars 👍 Super Unterstützung!
