### ISSUE TITLE
psurplus datafields shows values that not real and there. 

### ISSUE THREAD

**Issue by cracyfloyd** [iobroker-community-adapters/ioBroker.sma-em#709]
**Describe the bug**  
psurplus datafields shows values that not real and there. the datafields psurplus in L1/L2/L3 are all right and fine but the datafield psurplus sum are jumps in one second with values that not real. it shows the right value and two others with values 5000 and 8158,48.  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/57620791/64932a27-585c-4da4-a7a9-f193243b6fae

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 5.0.19
 - Node version: v18.19.0
 - Operating system: buanet/docker stable arm64 v9.1.0

**Additional context**

**Comment by cracyfloyd** [comment]
https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/57620791/1a59c940-c94e-42ed-bd16-14a7c88d4cdb

**Comment by cracyfloyd** [comment]
Erstmal danke für deine Rückmeldung. 
nun ein paar Antworten zu deinen Fragen.
zu 1. Elgris Smart Meter LAN 2.0
     2. Ja den Adapter habe ich vor 4 Wochen frisch installiert. Das Problem ist seit der Erstinbetriebnahme. 
     3. Kein Update
     4. Logfile beim start des Adapters:
        2024-02-05 17:44:30.659 - debug: sma-em.0 (3495) Redis Objects: Use Redis connection: 127.0.0.1:9001
2024-02-05 17:44:30.677 - debug: sma-em.0 (3495) Objects client ready ... initialize now
2024-02-05 17:44:30.718 - debug: sma-em.0 (3495) Objects create System PubSub Client
2024-02-05 17:44:30.718 - debug: sma-em.0 (3495) Objects create User PubSub Client
2024-02-05 17:44:30.737 - debug: sma-em.0 (3495) Objects client initialize lua scripts
2024-02-05 17:44:30.738 - debug: sma-em.0 (3495) Objects connected to redis: 127.0.0.1:9001
2024-02-05 17:44:30.749 - debug: sma-em.0 (3495) Redis States: Use Redis connection: 127.0.0.1:9000
2024-02-05 17:44:30.799 - debug: sma-em.0 (3495) States create System PubSub Client
2024-02-05 17:44:30.799 - debug: sma-em.0 (3495) States create User PubSub Client
2024-02-05 17:44:30.852 - debug: sma-em.0 (3495) States connected to redis: 127.0.0.1:9000
2024-02-05 17:44:30.884 - info: sma-em.0 (3495) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.sma-em, node: v20.11.0, js-controller: 5.0.19
2024-02-05 17:44:30.948 - info: sma-em.0 (3495) Options selected: Details L1 true Details L2 true Details L3 true Extended Mode false RealTime Interval 5 non-Realtime Interval 30 Language: de
2024-02-05 17:44:30.948 - info: sma-em.0 (3495) Listen via UDP on Network Interface eth1 with IP 192.168.10.250 on Port 9522 for Multicast IP 239.12.255.254
2024-02-05 17:44:32.497 - info: sma-em.0 (3495) New device discovered: SMA Energy Meter 1.0 S/N: 1900005930 with IP/port: 192.168.10.241/9522 message rate: 1/sec

Was ich komisch finde ist der Redis Eintrag. Hmmm. Redis hab ich garnicht in betrieb.

    5. Ein paar Bilder:

<img width="1064" alt="Bildschirmfoto 2024-02-05 um 17 49 39" src="https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/57620791/a3a79617-bdc6-42ba-b25e-398b2733bfde">

 
<img width="1099" alt="Bildschirmfoto 2024-02-05 um 17 49 05" src="https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/57620791/2691ae9b-6fea-4b97-96e8-d93c92d7f2e7">

  6. Ich nutze als Netz MacVlan (über Lan-Kabel) mit eigener IP für IOBroker.
  7.  Das kann ich garnicht genau sagen. Habe 3 unmanaged switches und ne Fritzbox7530AX. ob die switches igmpv3 und igmp snooping nicht beherschen weiss ich nicht. Mein Apple Universum mit Handy, AppleTV, Macbook, IMac,Pad klappt incl. Homebridge, yahka und der gleichen ohne Probleme.

Ich hoffe du kannst helfen. Falls du noch infos benötigst immer fragen.
Markus

**Comment by pdbjjens** [comment]
@cracyfloyd 
Da die Elgris EM schon bei einer anderen Installation mit schwankenden Mittelwerten aufgefallen sind, wäre mein erster Gedanke, dass es auch in diesem Fall die Ursache ist. 
Bitte probiere mal, das Echtzeit-Aktualisierungsintervall auf 0 zu setzen. Das schaltet die Mittelwertbildung aus. 
Die Elgris EM implementieren das zeitliche Verhalten der SMA-EM offenbar nicht exakt.

**Comment by cracyfloyd** [comment]
Leider keine Besserung.
Es ist ja auch nur dieser eine Datenpunkt. Nur noch einmal zur Info.

https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/57620791/383acb69-9347-4542-bbdf-ddacba947f69

**Comment by pdbjjens** [comment]
@cracyfloyd 
Ja, das ist in der Tat eigenartig. Hast Du schon einmal versucht, die Instanz inkl. Objektbaum zu löschen und wieder neu zu instanziieren?

**Comment by pdbjjens** [comment]
@cracyfloyd 
Dazu fällt mir spontan nichts ein. Vielleicht kannst Du dein damaliges Problem nochmal recherchieren.

**Comment by pdbjjens** [comment]
@cracyfloyd 
Noch eine Idee: Ist die Firmware vom Elgris EM aktuell?

**Comment by PilotOffTheWall** [comment]
Hallo Zusammen,

ich habe gerade mal meine Installationen überprüft. Leider kann ich momentan weder beim V1 noch beim V2 die Situation überprüfen, da an beiden Standorten bisher keine PV-Anlagen verbaut sind. Somit bleibt der Wert leer.
@cracyfloyd : du hast eine PV-Anlage installiert, oder?

Mir fällt auch nichts ein, womit ich kurzfristig Strom einspeisen könnte. Ein Balkonkraftwerk wirds da wohl nicht tun ;)

Der UPDATE-Prozess bei den Elgris SMs ist leider sehr manuell. Dazu muss man das Update bei Elgris anfragen und dann manuell installieren. Aber generell macht mir die Firmware eigentlich einen sehr soliden Eindruck.

Zusätzlich läuft mein V2 über Modbus, da Remote über VPN. Da wird der Datenpunkt nicht übertragen, wie mir scheint.

Falls euch eine Möglichkeit einfällt, wie das zu überprüfen ist, lasst es mich gerne wissen, dann sehe ich, ob ich es umsetzen kann.

**Comment by cracyfloyd** [comment]
> Hallo Zusammen,
> 
> ich habe gerade mal meine Installationen überprüft. Leider kann ich momentan weder beim V1 noch beim V2 die Situation überprüfen, da an beiden Standorten bisher keine PV-Anlagen verbaut sind. Somit bleibt der Wert leer. @cracyfloyd : du hast eine PV-Anlage installiert, oder?
> 
> Mir fällt auch nichts ein, womit ich kurzfristig Strom einspeisen könnte. Ein Balkonkraftwerk wirds da wohl nicht tun ;)
> 
> Der UPDATE-Prozess bei den Elgris SMs ist leider sehr manuell. Dazu muss man das Update bei Elgris anfragen und dann manuell installieren. Aber generell macht mir die Firmware eigentlich einen sehr soliden Eindruck.
> 
> Zusätzlich läuft mein V2 über Modbus, da Remote über VPN. Da wird der Datenpunkt nicht übertragen, wie mir scheint.
> 
> Falls euch eine Möglichkeit einfällt, wie das zu überprüfen ist, lasst es mich gerne wissen, dann sehe ich, ob ich es umsetzen kann.

Erst einmal herzlichen Dank. Dein Adapter scheint nicht das Problem gewesen zu sein. Ich habe Iobroker noch einmal neu aufgesetzt und ein Backup eingespielt und was soll ich sagen das Problem ist nicht mehr vorhanden. Du kannst mein Problem als gelöst betrachten. Tausend Dank für deine Mühe. 

Ansonsten, ja ich nutze eine PV Anlage und lese auch noch die Daten vom Elgris mit Modbus-TCP. Ich muss schon sagen das der Elgris sehr sehr zuverlässig und auch als Ersatz zu meinem alten SDM630 in Verbindung mit meinem Growatt Wechselrichter (Modbus SDM630 Modus) gute Dienste leistet.

**Comment by pdbjjens** [comment]
@cracyfloyd @PilotOffTheWall 
Danke an Euch beide für die Unterstützung bei der Lösung dieses Problems. 
Ich werde dieses issue nun als gelöst schließen. 
Falls Ihr noch  Bedarf an gegenseitigem Erfahrungsaustausch habt, könnt Ihr diesen Thread aber gerne weiter benutzen.
