### ISSUE TITLE
Fehler Invalid own IP address 192.168.179.101, please try another one from the Multicast Settings configuration panel

### ISSUE THREAD

**Issue by ZeroQool007** [iobroker-community-adapters/ioBroker.sma-em#722]
Hallo zusammen, ich habe seit kurzem folgende Fehlermeldung: `Invalid own IP address 192.168.179.101, please try another one from the Multicast Settings configuration panel` und ich kann mir nicht erklären warum. Der SMA HM2.0 ist online und auch unter der IP:

![image](https://github.com/iobroker-community-adapters/ioBroker.sma-em/assets/12768323/2fb7f86c-4d3f-4071-b190-6a60ce02a5be)

Hat jemand einen Tip? Danke

**Comment by ZeroQool007** [comment]
Habe den Fehler gefunden. Bitte den Code fixen: 

`						if (details.address === ownIP && !details.internal && (details.family === 'IPv4' || details.family === 4)) {
`

Family ist ein INTEGER und kein String mehr  bzw "IPv4", sondern nur noch 4.

**Comment by mcm1957** [comment]
Plase provide a PR.

**Comment by pdbjjens** [comment]
@mcm1957
Es gab offenbar eine Umstellung der family property in nodejs 18.0.0 von string auf number, die dann aber in nodejs 18.4.0 wieder rückgängig gemacht wurde. https://nodejs.org/api/os.html#osnetworkinterfaces (History aufklappen)

Aktuell (nodejs 18.4.0 und aufwärts) ist die family property ein String.

@ZeroQool007 
Welche nodejs Version setzt Du momentan ein? Löst ein upgrade von nodejs auf >= 18.4.0 das Problem?

**Comment by mcm1957** [comment]
Ok danke
Node 18.0.0 hab ich nicht gechecked. 😀
Hab nur in 22 20 u 18 gesehen dass string passen sollte.

**Comment by ZeroQool007** [comment]
> @mcm1957 Es gab offenbar eine Umstellung der family property in nodejs 18.0.0 von string auf number, die dann aber in nodejs 18.4.0 wieder rückgängig gemacht wurde. https://nodejs.org/api/os.html#osnetworkinterfaces (History aufklappen)
> 
> Aktuell (nodejs 18.4.0 und aufwärts) ist die family property ein String.
> 
> @ZeroQool007 Welche nodejs Version setzt Du momentan ein? Löst ein upgrade von nodejs auf >= 18.4.0 das Problem?

Muss ich später gucken. Auf jeden Fall 
Mache ich die node Updates nur mit dem iobroker Befehl. Somit weiß ich das die Version auf jeden Fall Supportes wird. Nichts desto trotz ist mein Fix eine Erweiterung und es spielt deshalb dann keine Rolle mehr welche Version genutzt wird, weil beide Varianten unterstützt werden. Gruß

**Comment by pdbjjens** [comment]
@ZeroQool007
Mich interessiert immer noch die Frage, ob ein upgrade von nodejs auf >= 18.4.0 das Problem bei Dir löst. Ich würde mich über Dein Feedback zu dieser Frage freuen.
@mcm1957 
Wenn das der Fall ist, müssen wir überlegen, ob es wirklich notwendig ist, diesen fix noch zu machen, da ab nodejs >= 18.4.0 das Problem nicht mehr existiert und es offenbar kaum user gibt, die nodejs  >= 18.0.0 <18.4.0 überhaupt noch einsetzen. Sonst hätten wir sicher mehr issues zu dem Thema.
Auf jeden Fall hätte dieser Fix m.M.n Zeit bis zum nächsten maintenance release Anfang 2025.

**Comment by mcm1957** [comment]
@pdbjjens 
Nein, der Fix - besser Workaround - macht wenig Sinn.
Empfohlene Node Version ist mittlerweile Node 20. Es sollte daher vollkommen ausreichen engines auf 18.4.0 anzuheben.

**Comment by pdbjjens** [comment]
Fixed with release v1.1.0
